{
  imports = [
    ./core
    ./desktop/common.nix
    ./desktop/fonts.nix
    ./desktop/hyprland.nix
    ./desktop/niri.nix
    ./desktop/plasma.nix
    ./desktop/sddm.nix
    ./desktop/greetd.nix
    ./desktop/gaming.nix
    ./hardware/bluetooth.nix
    ./hardware/battery.nix
    ./hardware/nvidia.nix
    ./network
    ./network/searxng.nix
    ./network/dae.nix
    ./network/clash-verge.nix
    ./network/localsend.nix
    ./dev/general.nix
    ./dev/embedded.nix
    ./dev/android.nix
  ];
}
