{ ... }:
{
  imports = [
    ./core
    ./apps/media.nix
    ./apps/communication.nix
    ./apps/qq.nix
    ./apps/wechat.nix
    ./apps/viewer.nix
    ./apps/productivity.nix
    ./apps/cc-switch.nix
    ./apps/codex-desktop.nix
    ./desktop/hyprland
    ./desktop/hyprland/components/hyprland.nix
    ./desktop/hyprland/components/quickshell.nix
    ./desktop/hyprland/components/appearance.nix
    ./desktop/hyprland/components/terminals.nix
    ./desktop/hyprland/components/shell.nix
    ./desktop/hyprland/components/applications.nix
    ./desktop/hyprland/components/services.nix
    ./desktop/niri
    ./desktop/niri/components/niri.nix
    ./desktop/niri/components/noctalia.nix
    ./desktop/niri/components/kitty.nix
    ./desktop/niri/components/fish.nix
    ./desktop/niri/components/fastfetch.nix
    ./desktop/niri/components/zed.nix
    ./desktop/niri/components/portal.nix
    ./desktop/niri/components/nyxmellow.nix
    ./desktop/niri/components/wallpapers.nix
    ./desktop/common/theme.nix
    ./desktop/common/fonts.nix
    ./desktop/common/xdg.nix
    ./desktop/common/input-method.nix
    ./desktop/terminals/foot.nix
    ./dev/tools.nix
    ./dev/omp.nix
    ./dev/uv.nix
    ./dev/vscode.nix
    ./dev/gdb.nix
    ./dev/codex.nix
    ./dev/claude-code.nix
  ];
}
